dashboard only requests taskPlans and taskWorks of currentAgent
root-systems/cobuy pull request #216
Opened 2017-10-17 01:14 UTC by iainkirkpatrick

Previously when loading the dashboard, all `taskPlans` and `taskWorks` in the database would be loaded and displayed - even those that don't belong to the current user. Now only those that belong to the current user are loaded.

In the future we will want to protect the routes themselves against unauthorised data access.

2017-10-17 10:09 UTC, NotThatSmith commented
Hmmm there seems to be an infinite loop when loading the dashboard.

Logged in as `test@test.nz` after a `npm run burnthemall` and `npm run burnthedb`

Screenshot of logs, there's hundreds of these:
![screenshot from 2017-10-17 11-04-44](https://user-images.githubusercontent.com/1152577/31659229-4cc6ee7c-b32b-11e7-9dde-6de3c3b4027d.png)

I suspect you're requerying when `taskWorks` is empty, even when it is intentionally empty (for a brand new user)?

2017-10-17 10:10 UTC, michael-smith-nz requested changes
comments above

2017-10-17 10:30 UTC, iainkirkpatrick commented
hmmm @NotThatSmith i'll check this out in the morning :)

2017-10-17 10:30 UTC, iainkirkpatrick commented
yay for manual testing tho!! :tada:

2017-10-17 22:03 UTC, iainkirkpatrick commented
ah so the problem is i didn't test this with a freshly burned db - infinite loop is because if there are no TaskPlans then `shouldQueryAgain` always returns true. will fix (somehow)

2017-10-17 22:16 UTC, iainkirkpatrick commented
actually that wasn't the problem - because at the moment a user always has an active task (though i can imagine in the future they might not, so this is something to think about). the problem was not guarding against querying again when the taskPlans request was in-flight (as per my understanding). fixed and re-pushed :)

2017-10-24 03:48 UTC, merged

2017-10-24 03:49 UTC, ahdinosaur commented
⛵️ 🌞