Feature/tapin demo seed data
root-systems/cobuy pull request #251
Opened 2017-10-24 20:23 UTC by iainkirkpatrick

Adds seed data for the upcoming Tapin demo:

- group
- supplier to the group
- members, including a group admin, which belong to the group
- products (resourceTypes, products, and priceSpecs) that the supplier supplies

The idea is that we can record a demo video without needing to go through and invite new members, write a bunch of product data each time - we can just log in as the various members on browsers and demonstrate the ordering / intent casting functionality.

2017-10-24 22:34 UTC, sarah-arrrgh requested changes

2017-10-24 22:34 UTC, sarah-arrrgh commented on db/seeds/tapin-demo.js
> +        relationshipType: i === 0 ? 'admin' : 'member',
@iainkirkpatrick - make dan a member

2017-10-25 00:58 UTC, ahdinosaur reviewed
looks good.

agree with @sarah-arrrgh that all group admins (only dan in this case) _must_ also be group members, so probably makes sense to create all member relationships then any special relationships.

2017-10-25 01:21 UTC, iainkirkpatrick commented
fixed :)

2017-10-25 02:48 UTC, merged